### ISSUE TITLE
Failing windows build

### ISSUE THREAD

**Issue by phadej** [igbinary/igbinary#115]
http://windows.php.net/downloads/pecl/releases/igbinary/2.0.1/logs/

**Comment by TysonAndre** [comment]
Are you familiar with how pecl is configured (by maintainers) for windows, since I'm not, and I don't see it documented on php.net or pecl.php.net?

This is linked to #37 

I can't see any documentation of how pecl builds are configured or what commands are used to execute them, and would probably recommend asking pecl-dev@lists.php.net or #winphp-dev why the folder pecl/apc still exists in php 7.0 windows builds

https://wiki.php.net/internals/windows is out of date.

The configure logs seem to enabling apc, while other extensions don't. It might be happening in buildconf (scanning config.w32), or might be unrelated to anything in the igbinary github repo.

The `make` step for 7.0 and 7.1 try to compile the apc extension first (C files), which obviously fails.

```
snapshot: forcing embed on
snapshot: forcing --disable-phpdbg-webhelper shared
snapshot: forcing apc-debug on
snapshot: forcing apc-filehits on
snapshot: forcing apc-spinlocks on
snapshot: forcing apc-memprotect on
snapshot: forcing apc-srwlock-native on
snapshot: forcing apc-srwlock-kernel on
```

**Comment by TysonAndre** [comment]
https://pecl.php.net/package/igbinary/2.0.1/windows has the DLLs
It's passing again. I assume php windows maintainers changed something, or other maintainers changed something.

http://windows.php.net/downloads/pecl/releases/igbinary/2.0.1/logs/

**Comment by phadej** [comment]
Great!
