### ISSUE TITLE
Segmentation fault serializing a recursive ArrayObject in PHP 5.3

### ISSUE THREAD

**Issue by pclifford** [igbinary/igbinary#15]
Running the following causes the process to run out of memory and segfault:

```
php -r '$o = new ArrayObject; $o->append($o); echo igbinary_serialize($o);'
```

A variation using PHP's serialize function completes successfully:

```
php -r '$o = new ArrayObject; $o->append($o); echo serialize($o);'
```

This is with PHP 5.3.3 and the current master (184e38c7a57f238bbc7263b0d8cb3099b6ec9208) version of igbinary.

**Comment by TysonAndre** [comment]
Closing all php 5 bugs - php 5's official security support ended in january 2019, and bugfix support ended in 2017 - https://www.php.net/supported-versions.php . No igbinary 2 releases are planned.

There haven't been any PRs for php 5 since these issues were filed, and I'm not that familiar with php 5's internals.
