### ISSUE TITLE
Redis Serialization > igbinary

### ISSUE THREAD

**Issue by Nirjonadda** [igbinary/igbinary#166]
Please can you let me know that how to enable Redis Serialization Support igbinary?

![screenshot00008](https://user-images.githubusercontent.com/6899856/36304408-d2efae8c-130f-11e8-8c5f-51cf2045fcec.png)

![screenshot00009](https://user-images.githubusercontent.com/6899856/36304519-43c7e520-1310-11e8-8149-5ab33fcd4ca1.png)

PHP Version 7.2.2

**Comment by TysonAndre** [comment]
https://github.com/phpredis/phpredis/blob/develop/README.markdown#installation

You have to compile or recompile redis with --enable-redis-igbinary

If you are using Windows, see http://php.net/manual/en/install.pecl.windows.php

**Comment by Nirjonadda** [comment]
@TysonAndre I am not using cPanel “PHP Pecl” Installer.

**Comment by TysonAndre** [comment]
Then build phpredis from source manually instead of using cPanel and install the phpredis.so/phpredis.dll file on your web host(s)

Probably something like https://thegeeksalive.com/install-php-pecl-redis-extension-on-cpanel-with-php-5-6-php-7-0/ for PHP 7 and adding --enable-redis-igbinary to ./configure

**Comment by TysonAndre** [comment]
Or contact your web server administrator to request that the do that.
