### ISSUE TITLE
5.4 and session.save_handler

### ISSUE THREAD

**Issue by jeff-minard-ck** [igbinary/igbinary#23]
I'm experienceing a very quirky behavior with igbinary, namely when fetching from memcache (using the memcache _NOT_ memcacheD extension) I will get raw binary data into the variable, but at random intervals I can't explain.

We have session.save_handler set to igbinary, and we use a custom session handling code that looks like this:

``` php
    /** Sets the session handling functions to our own */
    public function bindSessionFunctions() {
        session_set_save_handler(
            array(&$this, 'openSession'),
            array(&$this, 'closeSession'),
            array(&$this, 'readSession'),
            array(&$this, 'writeSession'),
            array(&$this, 'destroySession'),
            array(&$this, 'gcSessions')
        );
    }
```

Where that is a method of a class that has all the named functions as required.

We have some initializer code that does pretty basic gets, but what's driving me up the wall is this:

``` php
    $immediateMaintenance  = $mc->get("maintenance:siteid");
    $immediateMaintenance1 = $mc->get("maintenance:siteid");
    $immediateMaintenance2 = $mc->get("maintenance:siteid");
    $immediateMaintenance3 = $mc->get("maintenance:siteid");
```

Occasionally one of those variables will have raw binary strings from the session in them. XDebug shows something like this:

```
$immediateMaintenance3 = "\u0000\u0000\u0000\u0002\u00146..."
```

etc. It goes on much further, but the plaintext I can read out of it clearly marks it as what we're storing in memcached for the session.

If I comment out `session.save_handler = igbinary`, this error goes away.

Any ideas? Are we stuck not using igbinary for session encoding for the time being? 

This was not an issue in 5.3, and 5.4 changed some stuff pretty heavily around the internals of sessions with the introduction of [SessionHandlerInterface](http://www.php.net/manual/en/class.sessionhandlerinterface.php), so I have a sneaking suspicion that something between these things has gone a bit hay wire.

```
$ php -v
PHP 5.4.16 (cli) (built: Jun 18 2013 14:12:14)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans
    with test_helpers v1.0.1-dev, Copyright (c) 2009-2012, by Johannes Schlueter, Scott MacVicar, Sebastian Bergmann
```

and

```
$ php -m
[PHP Modules]
bz2
Core
ctype
curl
date
dom
ereg
fileinfo
filter
gd
gearman
geoip
gnupg
hash
iconv
igbinary
imap
json
libxml
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
soap
sockets
SPL
SPL_Types
sqlite3
standard
test_helpers
tidy
tokenizer
xdebug
xhprof
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
test_helpers
```

**Comment by EugenMayer** [comment]
We are experiencing a similar/same issue using 
 - PHP 5.5.20-1~dotdeb.1, 
- memcached (with igbinary support) 2.2.0 (compiled using pecl download ... ./configure --enable-memcached-igbinary )
 - memcached 1.4.13-0.2 dev

on a debian wheezy x64 and x68 server, using dotdeb php 5.5.

[21-Jan-2015 15:23:40 Europe/Berlin] PHP Warning:  igbinary_unserialize_long: end-of-data in 
[21-Jan-2015 15:23:40 Europe/Berlin] PHP Warning:  session_start(): Failed to decode session object.

--
We do also run igbinary 1.1.1 on php5.3 with session.serialize_handler = igbinary and experience no issues though, even though it might be, that it is not used due to this http://goo.gl/JYjaN5 ... compared to the new servers with php5.5, which are looking like this http://goo.gl/8qRn43 (igbinary 1.2.1).

So the difference might be for everyone, that session serialization is now finally happening, but def. is broken somehow.

Since we changed igbinary to 1.2.1 and also swapped php form 5.3 to 5.5, i cannot be sure that this is an PHP version issue, but somehow if rather doubt that.

**Comment by EugenMayer** [comment]
Just to keep things on track, we are working on in with Ted .. for now the important question is whether this works with 1.2.1

unserialize(session_encode()); or if sessions are serialized somehow different and unserialize (Which is of course also igbinary) is slighly different

**Comment by TysonAndre** [comment]
Closing all php 5 bugs - php 5's official security support ended in january 2019, and bugfix support ended in 2017 - https://www.php.net/supported-versions.php . No igbinary 2 releases are planned.

There haven't been any PRs for php 5 since these issues were filed, and I'm not that familiar with php 5.
