### ISSUE TITLE
Out of memory when unserializing in php 5.x

### ISSUE THREAD

**Issue by grom358** [igbinary/igbinary#45]
I have serialised a bunch tree structure per php source code and when reading them back I get PHP Fatal error running out of memory. Here is one such file:
https://www.dropbox.com/s/e423u3xrqa9o274/Variable.php.cache?dl=0

Using this file with the below code (to mimic the problem I get) results in out of memory.

```
<?php
$cache_filename = $argv[1];
$data = file_get_contents($cache_filename);
$i = 0;
while (true) {
  $tree = igbinary_unserialize($data);
  echo $i++, PHP_EOL;
}
```

**Comment by phadej** [comment]
Single `igbinary_unserialize` works fine though? as you have forever-loop in the example.

**Comment by grom358** [comment]
that forever-loop just to mimic the problem I get.. I have a foreach loop over numerous files. So my guess is memory is not being freed somewhere.

**Comment by phadej** [comment]
Can you try the same setup with standard `serialize` / `unserialize`? which PHP version you use?

**Comment by grom358** [comment]
```
grom ~: php --version
PHP 5.6.7 (cli) (built: Apr 15 2015 11:35:31) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

Yeah it works with standard serialize / unserialize (just uses 2.8Gb of disk and slow).

**Comment by grom358** [comment]
Does my supplied file in the loop never throw out of memory for you and just continues to loop fine?

**Comment by mrubiosan** [comment]
I'm having the same issue on PHP 5.5.25. In my case though I've a long running process using Redis configured to use igbinary as the serializer. If I switch to the PHP native serializer the memory leak disappears.

PHP 5.5.25 (cli) (built: Jun 22 2015 14:13:33) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

Linux 24a665d0e1b7 4.0.5-boot2docker

**Comment by zxzzxxzx** [comment]
Hello everyone,
just got the same issue with PHP 7.1.7. I need to igbinary_unserialize() the data stored in a file of 47.9M size.
Both native unserialize() and igbinary_unserialize() fail due to out of memory error. The code is rather simple:

`$data = file_get_contents($file);
$data = igbinary_unserialize($data); //out of memory occurs here  `

Any ideas how to fix it would be welcome. Thank you

**Comment by TysonAndre** [comment]
Are you able to provide the serialized file that fails and the classes it depends on (and their ancestor classes/traits/interface)?

Also, what is the maximum memory limit that you're using - Does it work with 2G or higher, for example?

Also,
- What igbinary version are you using?
- Does this still occur in PHP 7.1.26 - There have been a lot of bug fixes since 7.1.7

The PHP 5 issue is probably unrelated to the PHP 7 issue.

**Comment by zxzzxxzx** [comment]
Thank you for reply,

seems to be problem inside php server (currently I am using XAMPP). Will do upgrade to 7.1.26 and then try again

**Comment by TysonAndre** [comment]
Closing all php 5 bugs - php 5's official security support ended in january 2019, and bugfix support ended in 2017 - https://www.php.net/supported-versions.php . No igbinary 2 releases are planned.

There haven't been any PRs for php 5 since these issues were filed, and I'm not that familiar with php 5.
