### ISSUE TITLE
php5.3.x igbinary_unserialize

### ISSUE THREAD

**Issue by IYism** [igbinary/igbinary#53]
igbinary-1.2.1

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/redis.so' - /usr/lib64/php/modules/redis.so: undefined symbol: igbinary_unserialize in Unknown on line 0
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/memcached.so' - /usr/lib64/php/modules/memcached.so: undefined symbol: igbinary_unserialize in Unknown on line 0

**Comment by TysonAndre** [comment]
Try putting igbinary.so above memcached.so and redis.so in php.ini, so that igbinary.so is loaded before memcached.so and redis.so, so that igbinary's symbols are available (And making sure that extension=path/to/igbinary.so is in php.ini)?

```
...
extension=igbinary.so
extension=redis.so
extension=memcached.so
...
```

If this is reopened, include

- minimal php.ini
- full php version
- phpredis extension version, memcached extension version
